name: publish react native mazic components' docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  docs-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
        working-directory: ./docs
        run: |
          cd docs
          npm ci
          npm run build
          cd ..
          npm ci
          npm run deploy
